### ISSUE TITLE
Add a way to support the babel-plugin-module-resolver

### ISSUE THREAD

**Issue by silverlight513** [aziz/SublimeHyperClick#15] opened 2017-03-03 14:21 UTC
I use the babel-plugin-module-resolver in my project as I'm sure a lot of other people do too. I saw @aziz's response for the issue with webpack in https://github.com/aziz/SublimeHyperClick/issues/5. 

The likelihood of moving away from babel as browsers will always have different levels of support. Also unlike webpack the rc file is always in the same place with the same name so a user would not need to provide a location.

**Comment by aziz** [comment] 2017-05-13 18:50
in #5 @TylerK  suggested a workaround, doesn't it solve your issue?

**Comment by silverlight513** [comment] 2017-05-13 19:10
It probably will but that doesn't mean that hyperclick can't support webpack aliases

**Comment by aziz** [comment] 2017-05-13 20:40
Unfortunately, I'm pretty busy and I don't need this feature myself. PRs are always welcome.

**Comment by tomatau-sky** [comment] 2017-09-15 07:38
the plugin has also suggested a convention of adding a setting in a package.json to specify resolving directories:

```
  "moduleRoots": [
    "test",
    "src"
  ],
```

This would be a welcome standard for people who would like to use webpack without a babelrc but gain the same support from their editor.

**Comment by anru** [comment] 2017-10-19 10:54
With #26 PR merged you could use `lookup_paths` setting in order to specify `root` directories as it do babel-plugin-module-resolver. Alias setting isn't supported though

**Comment by SystemDisc** [comment] 2018-04-10 18:03
If I have a directory structure like so
```
./:
node_modules src other stuff

./node_modules:
module1 module2

./src:
file1.js someComponent

./src/someComponent:
index.js
```

and file1.js looks like:
```javascript
import module1 from 'module1';
import module2 from 'module2';
import someComponent from 'src/someComponent';
```

HyperClick fails to find `src/someComponent/index.js`

If I change
```javascript
  "vendor_dirs": {
    "js": ["node_modules"],
```
to:
```javascript
  "vendor_dirs": {
    "js": ["."],
```

HyperClick finds `src/someComponent/index.js` but no longer finds modules in node_modules

If I change it to:
```javascript
  "vendor_dirs": {
    "js": [".", "node_modules"],
```

HyperClick finds modules in node_modules again, but not `src/someComponent/index.js`

If I change it to:
```javascript
  "vendor_dirs": {
    "js": ["node_modules", "."],
```

HyperClick finds `src/someComponent/index.js` but no longer finds modules in node_modules

If I change it to:
```javascript
  "vendor_dirs": {
    "js": ["."],
```

and add to the lookup_paths array:
```javascript
  "lookup_paths": {
    "js": ["node_modules"],
```

HyperClick finds `src/someComponent/index.js` but still doesn't find modules in node_modules

I've tried several other combinations and different regular expressions to try and make this work, but I can't figure it out. Can you please explain how `vendor_dirs` and `lookup_paths` work, and add some documentation to the README?

**Edit**: I have determined that the cause is from me importing the `git` directory into Sublime and the high-level layout looking like this:
```
./git:
repogroup

./git/repogroup:
repo1

./git/repogroup/repo1:
node_modules src other stuff

./git/repogroup/repo1/node_modules:
module1 module2

./git/repogroup/repo1/src:
file1.js someComponent

./git/repogroup/repo1/src/someComponent:
index.js
```

If I change my settings to:
```javascript
  "vendor_dirs": {
    "js": ["node_modules"],
```
and
```javascript:
  "lookup_paths": {
    "js": ["repogroup/repo1"],
```
It works. However, I do not want to add an element to the array for each repo I have. Is there a better solution?

**Comment by SystemDisc** [comment] 2018-04-10 18:31
Ultimately, I should be able to set this:
```javascript
    "js": [
      "^import\\s+['\"]src/(.+)['\"];?$",
      "^import\\s+['\"](.+)['\"];?$",
      ".*from\\s+['\"]src/(.+)['\"];?$",
      ".*from\\s+['\"](.+)['\"];?$",
      ".*require\\(['\"]src/(.+?)['\"]\\).*",
      ".*require\\(['\"](.+?)['\"]\\).*"
    ],
```
and then set this:
```javascript
  "vendor_dirs": {
    "js": ["node_modules", "src"],
```
But, that does not work. Only the last item in the vendor_dirs array gets used for some reason.

**Comment by franciscolourenco** [comment] 2018-08-29 08:29
Would be great to also automatically pick up the following properties from `package.json`:

```
    "moduleRoots": [
        "src"
    ],
    "_moduleDirectories": [
        "src"
    ]
```

**Comment by cristianl** [comment] 2020-11-02 13:32
Closing: support for aliases has been available for a while [(see the config instructions for version 2.0)](https://github.com/aziz/SublimeHyperClick/issues/63#issuecomment-720145437) and native ES modules will be supported in the next release.

**Closed as completed by cristianl** 2020-11-02 13:32 UTC
